### ISSUE TITLE
Request for configuration instructions for scenario of Prosody server already existing and in use by Jitsi or other webapp

### ISSUE THREAD

**Issue by DalekDave** [JohnXLivingston/peertube-plugin-livechat#103]
First of all, thank you for your work on this cool and really valuable plugin for Peertube! :)

Version info
OS: Ubuntu 20.04 Server
Peertube version: 4.2.2
peertube-plugin-livechat version: 5.3.0
Prosody version ('apt list -a prosody'): focal,focal,now 0.11.4-1 amd64 [installed]

**Is your feature request related to a problem? Please describe.**
I have Peertube installed on a server on which I also have Jitsi installed (installed prior to Peertube - Jitsi was the original webapp requiring and installing Prosody).

When I install the peertube-plugin-livechat, and choose your default and preferred configuration ('Prosody server controlled by Peertube (recommended)', not the ones it says will be deprecated in version 6.0.0 of the plugin), the live chat is not working. You can currently see this at https://dalek.zone

FYI, I have actually had the peertube-plugin-livechat working before in this same context, but I had an unrelated server crash without having an available backup, and had to entirely re-install. Now, after a total server re-installation, I don't manage to figure out how I made it work before, and lots of googling has not led me to the solution. So I've previously demonstrated that peertube-plugin-livechat can indeed co-exist and work properly with Jitsi's Prosody setup.

**Describe the solution you'd like**
Please could you provide instructions about how to configure peertube-plugin-livechat with a previously-existing-and-operational Prosody installation?

I'd be happy to help out any way I can. We could do any testing you want at https://dalek.zone and I'll be glad to provide any additional information you need.

**Comment by DalekDave** [comment]
Update: I managed to get the chat working by changing the port it runs on. In the plugin's settings in the Peertube admin panel, I set the Prosody port to 5283, and in the file /var/www/peertube/storage/plugins/data/prosody-plugin-livechat/prosody/prosody.cfg.lua, I also changed the c2s_ports setting to 5283:

```
c2s_ports = {
  "5283";
};

```

**Comment by JohnXLivingston** [comment]
Hello,

Actually, your use case was exactly mine when I started working on this plugin. I also had Jitsi+Prosody on the server. 
That's why the plugin starts its own Prosody process, to avoid any conflicts with the Jitsi setup. By default, the plugin also use non-standards ports.

I think your problems is related to changes you made in the plugin settings, that leads to ports conflicts.
Here are default values I choosed for the plugin (you can try to set them back):
- prosody port: 52800
- Prosody client to server port: 52822 (if you enabled this option)
- Prosody external components port: 53470 (if you enabled this option)

If you still have issues using these settings, you can try the «diagnostic» button, at the beginning of the plugin settings. It will launch several tests, and write the result in your browser.

**Comment by JohnXLivingston** [comment]
> in the file /var/www/peertube/storage/plugins/data/prosody-plugin-livechat/prosody/prosody.cfg.lua, I also changed the c2s_ports setting to 5283:

Please note that if you changed this file manually, it will be overridden the next time your restart peertube, or save the plugin settings.

If you managed to fix your installation, please close this issue. Thanks.

**Comment by DalekDave** [comment]
Hello John, thanks for your comments, I will take note of them. And thanks for your work on this plugin, it's a really useful addition to Peertube. I did indeed get the live chat working, so I'll close the issue. :)

**Comment by JohnXLivingston** [comment]
> And thanks for your work on this plugin, it's a really useful addition to Peertube.

Thanks :)
