### ISSUE TITLE
Disable non Moderators or Disable groups

### ISSUE THREAD

**Issue by EkkiBrue** [JohnXLivingston/peertube-plugin-livechat#126]
![image](https://user-images.githubusercontent.com/6376844/208444200-d18a4585-6d96-452c-8558-5c64340a672e.png)

During a Chat I can't find a way to disable these "owners". I only want the Moderator to be available but I can´t see how I can get rid of the other 4 accounts.

Any help would be appreciated (probabyl I´m doing something wrong here) 
Or I´d like to request a feature to disable chosen accounts from the chat to be available or shown.

Only user logged in btw. is the moderator.

Thank you!

**Comment by JohnXLivingston** [comment]
These users are the instance moderator and admins. By default, there are moderators on chat rooms (because... there are the instance moderators).

Please note that only room moderators (the video creator and them) can see these accounts. Other users won't see them in the user list  (unless there are connected to the chat). 

You can change user access level, for example by using these moderation commands: https://conversejs.org/docs/html/features.html#moderating-chatrooms . You can also open the chat in a full page, open the top right menu, choose the «moderation» entry. I'm aware these screens are not easy to understand/user, I plan to work on that very soon.

This is (poorly) documented here: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/user.md#moderation . I plan to do better as soon as other major improvements will be done.


I'm closing the issue, but feel free to ask for other questions if needed.
