### ISSUE TITLE
Custom emoticon per channel

### ISSUE THREAD

**Issue by JohnXLivingston** [JohnXLivingston/peertube-plugin-livechat#130]
On twitch, streamers can add custom emoticons. So we should find a way to enable custom emoji (and it should be compatible with XMPP clients if possible, not only a ConverseJS hack).

- [x] The interface for streamers, where they can upload and delete their custom emoticons
- [x] The interface for viewers to use them
- [x] Displaying emoticon in the chat (ConverseJS, and XMPP clients if possible)
- [ ] Document this feature for stream viewers

Additional features, that were not listed when submitting to NlNet:

- [ ] #402
- [ ] #403

Reference: NlNet-task-18

**Comment by dannekrose** [comment]
This would be a great feature as people do try to migrate off Twitch or other services to PeerTube.

**Comment by dannekrose** [comment]
By-the-way, I did manage to do this at a global instance level and I'm not sure how it would work on a per-channel basis given how conversejs works.

The files I edited were the following:

converse.min.js

This is section I edited there:

emoji_categories:{smileys:":grinning:",people:":thumbsup:",activity:":soccer:",travel:":motorcycle:",objects:":bomb:",nature:":rainbow:",food:":hotdog:",symbols:":musical_note:",flags:null,custom:":converse:"}

I made flags null because depending on the client, the icons show up on 2 lines if I don't.

I then changed custom to :converse: but this can be anything.

Then the second file (the more important one) is the emojis.js

Since I didn't want to hack around the "source" for this, I just edited the JSON in the file that's generated.

```
module.exports = JSON.parse('{"custom":{":converse:":{"sn":":converse:","url":"/client/assets/images/custom_emojis/converse.png","c":"custom"},":xmpp:":{"sn":":xmpp:","url":"/client/assets/images/custom_emojis/xmpp.png","c":"custom"}, ... <other custom emojis added here> ... ,"c":"custom"}},"smileys":{":smiley:":{"sn":":smiley:","cp":"1f603","sns":[],"c":"smileys"},"
```

Then, I put the emojis into the 
/var/www/peertube/versions/peertube-v6.0.3/client/dist/assets/images/custom_emojis/<channel_name> 

folder(s).  This gives the URLs /client/assets/images/custom_emojis/<channel_name>/<emoji_file.png> which is used in the emojis.js file.

Based on the converseJS documentation, it seems like converse can only support one Custom category for Emojis.

https://conversejs.org/docs/html/configuration.html?highlight=emoji#emoji-categories

```
Due to restrictions intended to prevent addition of undeclared configuration settings, it’s not possible to add new emoji categories. There is however a custom category where you can put your own custom emojis (also known as “stickers”).
```

**Comment by dannekrose** [comment]
To do this on a "per-channel" basis, I imagine that there would have to be separate conversejs compiled bundles for each separate channel.  

Maybe that's easy to do (I'm not sure about how the prosody server would have be set up) or might not be, but if each channel could get their own separate coversejs and emojis code bundles, I could see this possibly working.

**Comment by dannekrose** [comment]
If it makes sense, it might be worth considering the Movim front-end.

https://github.com/movim/movim

It has way more features than what's needed here, but it has built-in support for easily updating and adding custom "stickers", as well as being able to do PubSub which might allow you to do "Pinned Chat Messages" that show always at the top of the chat list.

It might be too hard to integrate at this point (You're done a lot of work already getting ConverseJS working very well) so I just mention this as something of an FYI only, not as any kind of request to try using it.

**Comment by JohnXLivingston** [comment]
Thanks @dannekrose for your tips. As said on the support chat room, i do not exclude to modify ConverseJS code to add this feature (either by overring the emoji module, or by completly rewriting a module).

**Comment by JohnXLivingston** [comment]
@dannekrose : for the record: https://github.com/conversejs/converse.js/pull/3405
New hook in ConverseJS, so we can change the json file at runtime.
I start working on the custom emoji feature today.

**Comment by JohnXLivingston** [comment]
@dannekrose : custom emojis per channel are done!
The plugin will not be released for now, we have some cleaning to do on other features.

I did not add custom emojis per instance for now. It took me too long to implement per channel emojis. I have to find some sponsorship to work on it (or if another contributor want's to work on it...)
I opened a new issue for this: https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/403

Feature is documented here: https://johnxlivingston.github.io/peertube-plugin-livechat/documentation/user/streamers/emojis/
