### ISSUE TITLE
Wrong message timecode?

### ISSUE THREAD

**Issue by JohnXLivingston** [JohnXLivingston/peertube-plugin-livechat#141]
**Describe the bug**
During a live with 450 viewers, the streamed version of the chat lagged. Messages were displayed with more than 10 minutes late.
See https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/142

But the timecode near the message was the current date, not the message date.
This was confusing, and the streamer did not notice the lag because of this.

**Expected behavior**
Date should be the message date, not the displayed date.
I don't know if the lag was on the backend server, or in the browser.
I have to investigate.

Reference: Related to NlNet-task-10

**Comment by mwild1** [comment]
This is a tricky one, because you can't just trust the timestamp of the sending client (it could be seconds, minutes hours or more incorrect). If the lag was affecting the server's acceptance of messages, the server doesn't know how long ago the user typed the message, and cannot correct the timestamp.

Once the server has a message, it could timestamp it though, and include this timestamp in the message delivery.

The real fix, of course, is to fix the lag.

**Comment by JohnXLivingston** [comment]
I don't know for now where was the lag.
My browser was ok. Others users too (I think). Just the browser used by the streamer in OBS was 10 or 20 minutes late.

Thanks for your message.

**Comment by JohnXLivingston** [comment]
I made some tests:

https://github.com/JohnXLivingston/livechat-perf-test/tree/main/tests/10-browser-vs-flooding-bot

These tests seems to confirm that the lag could be caused by the browser CPU usage.
The fact that the lag was not the same for all users is another clue.

I'm closing this issue.

Note: could also be some backend lag, this will be tested later on, when i'll work on https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/178
