### ISSUE TITLE
CSS Styling where?

### ISSUE THREAD

**Issue by EkkiBrue** [JohnXLivingston/peertube-plugin-livechat#148]
Hi John and co ;)

We are planing for an event next week and it will be the first time we use the Chat-Plugin for a larger audience >200 ppl - I´m really looking forward to use it. 

My question now relates to styling of the chat window. I tried to change some CSS in Peertube (Admin / Config / Advanced / CSS) to fit our Website CI an get it displayed in the the converse.js theme. Somehow the changes made in the peertube css are not reflected in the plugin. Is there a frontend way to change the css styling somewhere ? Or have I missed something

I try to change the following CSS

.conversejs .chatbox .bottom-panel .sendXMPPMessage .chat-textarea {
    color: #ffffff;
    background-color: #003c71;
}

It would be a blast to have some custom fields to reflect changes for CSS styles.

All the best and thanks again for this project and all the time you put in here.

**Comment by JohnXLivingston** [comment]
Hello @EkkiBrue ,

Your custom CSS does not apply, because for now the chat is in an iFrame.

And for now, I don't really allow CSS changes in this iframe, because I have many DOM changes to come, and it would be difficult to not break any custom CSS that users would have done.

The chat plugin uses the Peertube CSS variables to select its colors.

So, if you want to reflect your color changes, just override these CSS variables in your custom Peertube CSS:

```
--mainForegroundColor
--mainBackgroundColor
--greyForegroundColor
--greyBackgroundColor
--menuForegroundColor
--menuBackgroundColor
--inputForegroundColor
--inputBackgroundColor
--mainColor
```

And check in the Plugin settings that you have the theme set to `Peertube theme`, and 
`Automatic color detection` enabled.

This should work. If not, please share your instance url so I can check your CSS.

**Comment by EkkiBrue** [comment]
Thank you!

I switched theme to peertube and turned automatic color detection on.
Looks better in the first place until I switch on the EMOTICONS. This is completly garbaged (contrast strange, etc.). I´m displying the PT Video and the chat in IFRAMEs on our wordpress and now I have to get both layouts to fit each other (PT and WP).

![image](https://user-images.githubusercontent.com/6376844/216021202-646d5edd-247a-4797-9f4c-efd1ec7f1c6e.png)

So I switched back to converse.js concorde as it looks much better.

![image](https://user-images.githubusercontent.com/6376844/216021474-33cf38c5-8442-4035-a15f-7484603fbbe0.png)

So last question: Dan I change the basecolor of the ICONS (Send, Menu and Emoticon) from Orange to something else the easy way ? I guess not or just via the hack recommended by you;)

You can take a look: 
https://www.medienzentrum-harburg.de/m2m-live-chat/

peertube is
https://video.medienzentrum-harburg.de

**Comment by JohnXLivingston** [comment]
> I´m displying the PT Video and the chat in IFRAMEs on our wordpress and now I have to get both layouts to fit each other (PT and WP).

Oh, you didn't mention your are displaying the chat in Wordpress. So you have another way to customize the colors.

Switch back the theme to `peertube`. Then, use this kind of code for your iframe:

```html
<iframe src="https://video.medienzentrum-harburg.de/plugins/livechat/6.0.0/router/webchat/room/e89079bc-62e3-4fee-a40d-2a47d5293db7?_ac_mainForeground=%23212529&_ac_mainBackground=%23fff&_ac_greyForeground=%23585858&_ac_greyBackground=%23E5E5E5&_ac_menuForeground=%23fff&_ac_menuBackground=%23000&_ac_inputForeground=%23212529&_ac_inputBackground=%23fff&_ac_buttonForeground=rgb%28255%2C+255%2C+255%29&_ac_buttonBackground=hsl%2824deg%2C+90%25%2C+50%25%29&_ac_link=%23212529&_ac_linkHover=%23212529"  sandbox="allow-same-origin allow-scripts allow-popups allow-forms" width="460" height="612" frameborder="0"></iframe>
```

To get the url with all parameters: when you are on peertube, above the chat, the video's owner can see a «share» button.
The popup that opens has an option «use current theme colors». Checking this option creates a link with all these parameters.
You have one parameter per color. Each of these parameters is associated to one CSS variable (see the list in my previous response).

![image](https://user-images.githubusercontent.com/38844060/216026188-081c0831-c336-4db4-bda5-ce698ee7165b.png)


You have to provide all parameters, with valid CSS color values, correctly url-encoded. Otherwise you will fallback to the default colors.

You can then change colors, if you want different colors for the wordpress embeded chat.

I don't know if this will allow you to correct the background color for the emoticons. Peertube mainly uses less differents colors concept as ConverseJS (the chat library)... So it is difficult to have everything working fine with all possible Peertube themes (including dark theme variations).

**Comment by EkkiBrue** [comment]
Thanks a lot. I´ll try this!

**Comment by JohnXLivingston** [comment]
@EkkiBrue , as you are planning to do a live with >200 users, I just released a v6.1.0 version.

It has some modifications that will improve the user experience.
See the changelog: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/CHANGELOG.md#610

If you don't want to wait for your instance to index the new version (which can last 12 or 24 hours), you can do this modification in the database:

```
sudo -u peertube psql peertube_prod
peertube_prod=> update "plugin" set "latestVersion" = '6.1.0' where "plugin"."name" = 'livechat';
UPDATE 1
```
Then you will have the button to upgrade in your plugin list.

**Comment by JohnXLivingston** [comment]
And in this version, in the «share» popup you will have on option to generated an iframe.
See https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/110

**Comment by EkkiBrue** [comment]
Love you! ;) Thanks a lot!!! Have to leave for some days and will migrate this on the weekend ;) Thanks for all your help so far!!!
