### ISSUE TITLE
Cannot import or register plugin livechat on Perrtube 5.1.0-rc.1

### ISSUE THREAD

**Issue by rnek0** [JohnXLivingston/peertube-plugin-livechat#158]
**Describe the bug**
Error on last day with Perrtube 5.1.0-rc.1  

error[06/03/2023 02:13:23] Client log: Cannot import or register plugin livechat
{
  "tags": [
    "client"
  ],
  "userAgent": "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.177 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
  "meta": "{\"message\":\"Unknown server error\",\"headers\":{\"normalizedNames\":{},\"lazyUpdate\":null,\"headers\":{}}}",
  "url": "https://ptb.lunarviews.net/w/cd5d0fd7-a40d-4685-b417-cd302948c1eb"
}

Url are not an url for live chat

**Expected behavior**
No error on logs for Android 6.0.1; Nexus 5X Build

**Server :**
 - Debian GNU/Linux 11 (bullseye)
 - Peertube version: 5.1.0-rc.1
 - Peertube installation type: standard
 - peertube-plugin-livechat version: 6.1.0

**Plugin diagnostic:**
[«diagnostic»](https://gist.github.com/rnek0/c2e1662e6dccb309ff49d80d9d20e0cb)

**Additional context**
Update to rc1 version with update script from last stable vesion.  
It is possible that I don't have the right settings in my config, or that it comes from Peertube's 5.1.0-rc.1. This is not a live, it may be a log error.

**Comment by JohnXLivingston** [comment]
I can see similar logs on my server. I think this is nothing serious.

The «tags: client» means that this is a log that was on the client side. Indeed, since [Peertube 4.3.0](https://github.com/Chocobozzz/PeerTube/blob/develop/CHANGELOG.md#v430), client can send logs to the server, so that admin can check what happened on the client side. This can be disabled by modifying the server conf.

The error log itself means that the client was unable to load the javascript from the plugin.

The user agent in the log says that it is a google bot that was parsing the instance. My hypothesis is that the google bot does not support all javascript module formats. So it loaded the Peertube code, but throw an exception when loading plugins code. This exception was catched by the logging system and sent to the backend.

As long as this kind of logs is only triggered by google bot, it is not an issue.
