### ISSUE TITLE
Anonymous login problem

### ISSUE THREAD

**Issue by Alterak** [JohnXLivingston/peertube-plugin-livechat#20]
I don’t want to wait for instructions.
I still managed to install and configure the Prosody server. If you use authorization by default, then everything works fine, you can check it yourself ...
conference.chat.peervideo.ru

User: test
Password: 12345678

BOSH also works https://chat.peervideo.ru:5281/http-bind/

If you try your configuration, then the connection to the server does not work ... When connecting, error
"The server does not use any language of the used authentication method"

But if I comment out these two lines then everything works well
```
--      authentication = "anonymous"
--      allow_anonymous_s2s = false
```

**Comment by JohnXLivingston** [comment]
I just commit this tutorial: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/tutorials/prosody.md

It worked for me on a fresh installation.

Removing authentication=anonymous means that users must have accounts on the xmpp server. That is not what I want.

**Comment by Alterak** [comment]
> I just commit this tutorial: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/tutorials/prosody.md
> Sorry for the delay, I have been very busy this week.
> 
> It worked for me on a fresh installation.
> 
> Removing authentication=anonymous means that users must have accounts on the xmpp server. That is not what I want.

I have the same configuration but doesn't work!
Can you post the main config file /etc/prosody/prosody.cfg.lua ?? It seems to me that there are errors in this file, although I am nothing in it, just added administrators and that's it.

**Comment by JohnXLivingston** [comment]
Have you also the same nginx configuration?

My /etc/prosody/prosody.cfg.lua is the default one. It is a fresh Debian Buster installation.

**Comment by JohnXLivingston** [comment]
And please check the prosody virtualhost name and the muc component name. There are some changes between this tutorial and the previous example file.

**Comment by Alterak** [comment]
Sorry, but if it is so very difficult to configure, it is a very bad idea to use this Prosody server ... Moreover, the protocol and the server are very old technology. In terms of our development towards P2P, but at the same time, we are trying to make a very outdated chat- (
The access was from Peertube, not the internet. There are a lot of instructions on the Internet on how to create a chat in Python, I'm not a very good programmer, but I'll try to write my idea. Thank you for your hard work.

**Comment by JohnXLivingston** [comment]
XMPP is an old protocol, but it is still actively used (skype for example). Like IRC (used by twitch for example), that is older than the web!
Prosody is still maintained (last version was published a month ago) and is very robust. It allows advanced moderation and many other tools. That's why I choose this technology. 

> I need to access the chat or the chat server from Peertube, not from the Internet. 
By following the tutorial, it is your peertube server that serves the data. The peertube nginx service work as a reverse proxy for the prosody backend. Clients do HTTP requests (or Websocket) to your peertube server. 

If you want to do your own webchat, go ahead. You can configure any url to be included in the iframe. The ConverseJS/Prosody part is totally optional. 

I'm closing this issue. I hope you will find a solution that fits your needs.
