### ISSUE TITLE
Developing the plugin require Debian-only tools

### ISSUE THREAD

**Issue by tytan652** [JohnXLivingston/peertube-plugin-livechat#200]
**Describe the bug**
appimage-builder fail because it requires Debian-only tools (`dpkg-deb` and `apt-get`).

**To Reproduce**
1. Use ArchLinux btw
2. Install needed dependencies (nodejs, npm, python…)
3. Clone the repo recursively 
4. Do a `npm install`
5. See appimage-builder fail because `dpkg-deb` is missing.

**Expected behavior**

Documentation explain that a Debian-based environment is required because of the appimage-builder relying on Debian packages.

**Additional context**
ArchLinux provide the `dpkg-deb` executable with the `dpkg` package, but appimage-builder will then fail because `apt-get` is missing.

You can install `apt` through this [AUR](https://aur.archlinux.org/packages/apt) package, but it needs to fix `perl-xs-parse-keyword` package source url to fix building and it requires knowledge about ArchLinux packaging.

So yes it works on ArchLinux if `dpkg` and `apt` are installed.

**Comment by JohnXLivingston** [comment]
Some notes for myself: move the appimage in another project?

**Comment by JohnXLivingston** [comment]
Waiting for a proper fix, I documented it there:
https://johnxlivingston.github.io/peertube-plugin-livechat/contributing/develop/#prerequisite-for-building-this-plugin

**Comment by JohnXLivingston** [comment]
Fixed by https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/200 

Now, the AppImage is build in another project: https://github.com/JohnXLivingston/prosody-appimage
This project still needs Debian to be build.

The build script now downloads binaries from https://github.com/JohnXLivingston/prosody-appimage/releases/tag/v0.12.3-1 attachments
The binary sha256 sums are compared, to be sure there is no third party that can modify the files.
If everything ok, the binaries are copied in the `dist` dir, and included in the livechat plugin releases.
