### ISSUE TITLE
Please do a video walk-through from a clean instance to having a fully working peertube-livechat plugin working.

### ISSUE THREAD

**Issue by scramblr** [JohnXLivingston/peertube-plugin-livechat#27]
**Is your feature request related to a problem? Please describe.**
The documentation, although updated and more clear than before, is still not clear enough to get a running server. Please do a quick video screenscapture of the installation and configuration of LIVECHAT to help put a stop to all of the confusion.

**Describe the solution you'd like**
A simple video that runs through all of the documentation and shows a "completed product" in order to capture some nuance or detail that may have slipped past the documentation.

**Describe alternatives you've considered**
Doing a video myself, but I have had issues with configuration so far.

**Additional context**
N/A

**Comment by JohnXLivingston** [comment]
Hello,
I am aware that the installation of this plugin is currently not very simple. I have some ideas to make it easier (and to make it fully automatic). But in order to have the time to work on it, I need to find some funding. I have a serious lead, and high hopes to be able to get to work in early April. I will get back to you very soon.
Thanks for your interest.

**Comment by JohnXLivingston** [comment]
Hello,

The new version of the plugin is out! (v2.0.2)

See here for the installation procedure: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md

The only thing you have to do on your server is in the Prerequisite section https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md#prerequisite .

Then go to the plugin settings, and check «use the builtin prosody xmpp server». You can ignore all settings after this checkbox.

Hope this helps.

Best regards,
John

**Comment by dhk2** [comment]
The prosody install process is a vast improvement in terms of end user ease of use, bravo

**Comment by JohnXLivingston** [comment]
> The new prosody install process is a vast improvement in terms of admin ease of use, bravo

Thank you, it's nice to hear!

**Comment by scramblr** [comment]
Thanks for the updates, they do help - I can successfully have chat working on my instance, however looking at the console it definitely is relying heavily on a localhost configuration, instead of the instance domain and keys. Is this intended? Also, the guide appears to be mixing both the new and old instructions together (for example https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/converseJS.md is 404, but if you manually browse to that documentation folder, the converseJS documentation refers to the old configurations.)

This is mainly why I was inquiring about a 'top to bottom' 2-3 minute video showing the steps. They are still currently a bit out of order and confusing.

**Comment by JohnXLivingston** [comment]
Thanks for reporting the deadlink.

Localhost is intended, yes. With the new «builtin prosody mode», the Peertube instance act as a reverse proxy. The Prosody process only listen on localhost port, so that it can't be accessed from the outer world. Connections go through the Peertube instance.

I know that there is a lot of work to clean the documentation (and get a simplier settings screen), and it will be done. I just need more time. 

As said here https://github.com/JohnXLivingston/peertube-plugin-livechat#peertube-plugin-livechat , there are 3 different way of using this plugin. The first is the easiest and straightforward: https://github.com/JohnXLivingston/peertube-plugin-livechat/blob/main/documentation/prosody.md . 
The 2 others are for admins that want to have a more flexible configuration. To use another backend, or to have better scalability. 


I plan a lot of work on this plugin in the next weeks. So if I make a video now, it will be deprecated in 2 weeks. Be sure I will try to make things simplier, and clean the documentation.

Thanks for your interest. 
I'm closing this issue, but feel free to continue the discussion.

**Comment by scramblr** [comment]
Ok thank you for clarifying that - I've been pulling out my hair for the better part of a day trying to figure out why I can't make this recognize my domain name vs. localhost! I completely understand on your hesitancy on making the video and will just wait, now that I know 'localhost' is fully expected. It just looks wrong, but it works fine so that's all I need for now! Keep up the great work!

**Comment by JohnXLivingston** [comment]
Glad to hear that it is working for you. 
I was in a hurry when I first released this plugin, because I needed it for live webinars. Now I have to clean the plugin, and make it simpler :)
For the record, I added a diagnostic tool: at the beginning of the settings page, there is a link «launch Diagnostic». It will display debugging informations on your instance configuration. 
NB: only instance admins can access this page.

Its look like that:
![image](https://user-images.githubusercontent.com/38844060/115548782-27bf8380-a2a8-11eb-88fb-176ec014f6fb.png)
